- name: Corporate Law
  description: We offer progressive counsel cutting across several industries including financial services,private equity,energy,mining and infrastructure,education and technology.

- name: Litigation
  description: We are dedicated to protect your interests in a wide range of matters including personal injury,employment disputes,commercial disputes and land matters.

- name: Intellectual Property
  description: We are committed to protect your ideas with specialized IP legal consultancy.

- name: Conveyancing
  description: We handle all matters land with utmost professionalism and dedication.

- name: Tax Law
  description: We offer tax advisory to commercial entities.
